### ISSUE TITLE
Connection corrupt due "Packet corrupt"

### ISSUE THREAD

**Issue by liuchu** [nccgroup/SocksOverRDP#11]
### Situation
WIN1: My PC, the RDP client.
WIN2: A jump server, the RDP server.
SERVER: A linux server which can`t accessed by WIN1, but can accessed by WIN2:

### Issue
Using this software, WIN1 can access SERVER successfullly, this is great! But the connectivity doesn't seem verty stable, I got below error after connected for a while.
```
Server sent disconnect message
type 2 (protocol error):
"Packet corrupt"
```
Can this issue be solved at "software" level?

**Comment by earthquake** [comment]
This isn't a well written bug report. So many things are missing and also it seems to be a software issue rather than the module's.
The connection over SOCKS correlates with your connection over RDP. I had no packet loss on the tunnel, so it is unlikely that the module is buggy. If it is, I would need access to the environment to reproduce it.

**Comment by earthquake** [comment]
No response, closing this
