### ISSUE TITLE
Can the Server side executable add the ability to connect to the Socks/Http proxy?

### ISSUE THREAD

**Issue by liruoyu2008** [nccgroup/SocksOverRDP#14]
This plugin is great! It solves my big problem.
But, Can the Server side executable add the ability to connect to the Socks/Http proxy? 
In this way, a proxy chain can be formed. The client plug-in provides the Socks proxy service, and then flows to the server through the DVC. Finally, the Socks/Http proxy egress traffic of the server environment is equivalent to mirroring the proxy of the server to the client. 
In this way, we can configure the server proxy to enable the client to enjoy more diversified proxy functions. 
It's an exciting thing to think about! Just my C++ is not good enough. This idea is a bit of an impotence for me

**Comment by CR-DMcDonald** [comment]
> This idea is a bit of an impotence for me

Really? It excites me.

**Comment by liruoyu2008** [comment]
Of course! I recently encountered a scenario that required implementation in this way. However, I'm not familiar with C++, let alone using it to implement logic related to network communication.

**Comment by earthquake** [comment]
I'm not sure I fully understand your idea, since it seems to me that is actually what the plugin does. Socks can be chained, you can use for example proxychains to do that. The main aim of this tool to tunnel traffic over DVC both direction, which is achieved already.

Not to mention that I've left NCC Group about a year ago and will not contribute to this repository anymore. Any new tools are going on my private github. Will leave this thread open for now to get a better idea what you'd need, but otherwise will close this.

**Comment by liruoyu2008** [comment]
I mean, assuming that the server has a socks agent running on 127.0.0.1:1080, can the server's SocksOverRDP.exe program use this agent for network access without other tools? This is as if the socks agent of the server is transparently passed to the client through DVC by SocksOverRDP suit.

**Comment by earthquake** [comment]
proxy chaining is exactly you described. You configure your client to connect to the server's localhost on port 1080. Easy peasy. I recommend you to read the RFC about Socks v5. Will close this "issue" now.

**Comment by liruoyu2008** [comment]
OKay，thank you！
